# Generated by Django 2.0.7 on 2019-12-20 01:42

from django.db import migrations, models
import utils.files_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=1000, null=True)),
                ('annonce', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.FileField(upload_to=utils.files_utils.upload_file_location_slide)),
            ],
        ),
    ]
