# Generated by Django 2.0.7 on 2019-12-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_auto_20191220_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
