# Generated by Django 2.0.7 on 2019-12-23 13:51

from django.db import migrations, models
import utils.files_utils


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_slide_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baniere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce', models.CharField(blank=True, max_length=1000, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('lien', models.URLField(blank=True, max_length=1000, null=True)),
                ('image', models.FileField(upload_to=utils.files_utils.upload_file_banniere)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banière',
                'verbose_name_plural': 'Banières',
            },
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
    ]
