# Generated by Django 2.0.7 on 2019-12-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_auto_20191223_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='baniere',
            name='niveau_baniere',
            field=models.CharField(choices=[('niveau_un', 'Niveau un (1)'), ('niveau_deux', 'Niveau deux (2)'), ('niveau_trois', 'Niveau trois (3)'), ('niveau_quatre', 'Niveau quatre (4)')], default='Niveau un (1)', max_length=250),
            preserve_default=False,
        ),
    ]
