# Generated by Django 2.0.7 on 2019-12-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_baniere_niveau_baniere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baniere',
            options={'verbose_name': 'Bannière', 'verbose_name_plural': 'Bannières'},
        ),
    ]
