# Generated by Django 2.0.7 on 2018-09-07 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_payementlivraison'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressPayementLivraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_payement_livraison_type', models.CharField(choices=[('facturation', 'Facturation'), ('livraison', 'Livraison')], max_length=120)),
                ('address', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('pays', models.CharField(max_length=250)),
                ('etat', models.CharField(max_length=250)),
                ('ville', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=250)),
                ('payement_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.PayementLivraison')),
            ],
        ),
    ]
