# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-11 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='outcom',
            new_name='outcome',
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='outcom_type',
            new_name='outcome_type',
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='refused',
            new_name='refunded',
        ),
    ]
