# Generated by Django 2.0.7 on 2019-05-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='taxe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
