# Generated by Django 2.0.7 on 2019-03-23 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20190323_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantite',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Product'),
        ),
    ]
