# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='suscribed',
            new_name='subscribed',
        ),
    ]
