# Generated by Django 2.0.7 on 2019-01-21 19:06

from django.db import migrations, models
import marketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_marketingpreference_mailchimp_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slider', models.ImageField(max_length=250, upload_to=marketing.models.upload_product_file_loc)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
