# Generated by Django 2.0.7 on 2019-09-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(default='I Tag you', max_length=250),
            preserve_default=False,
        ),
    ]
