# Generated by Django 2.0.7 on 2019-09-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_tag_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_product_type',
            field=models.CharField(default='phone', max_length=250),
            preserve_default=False,
        ),
    ]
