# Generated by Django 2.0.7 on 2019-07-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Souhait des utilisateurs ', 'verbose_name_plural': 'Souhaits des utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='wish',
            name='name',
        ),
    ]
