# Generated by Django 2.0.7 on 2019-03-23 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20190323_0314'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurshasepayementlivraison',
            name='product',
        ),
        migrations.AddField(
            model_name='productpurshasepayementlivraison',
            name='cart_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts.CartItem'),
            preserve_default=False,
        ),
    ]
