# Generated by Django 2.0.7 on 2018-07-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180731_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
