# Generated by Django 2.0.7 on 2019-04-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190328_2355'),
        ('orders', '0002_auto_20190323_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurshasepayementlivraison',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpayementlivraison',
            name='facturation_address_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpayementlivraison',
            name='livraison_address_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpurshasepayementlivraison',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
