# Generated by Django 2.0.7 on 2019-04-17 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190417_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurshasepayementlivraison',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
