# Generated by Django 2.0.7 on 2018-07-31 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_digital',
        ),
    ]
