# Generated by Django 2.0.7 on 2018-07-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productpurshase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurshase',
            name='user',
        ),
        migrations.AddField(
            model_name='productpurshase',
            name='order_id',
            field=models.CharField(default='abc123', max_length=120),
            preserve_default=False,
        ),
    ]
