# Generated by Django 2.0.7 on 2018-07-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180731_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurshase',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='productpurshase',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductPurshase',
        ),
    ]
