# Generated by Django 2.0.7 on 2018-07-31 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_productpurshase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurshase',
            name='billing_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile'),
            preserve_default=False,
        ),
    ]
