# Generated by Django 2.0.7 on 2018-08-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180812_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpurshase',
            old_name='update',
            new_name='updated',
        ),
    ]
