# Generated by Django 2.0.7 on 2018-08-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180812_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100),
        ),
    ]
