# Generated by Django 2.0.7 on 2018-08-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180830_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
    ]
