# Generated by Django 2.0.7 on 2018-09-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderpayementlivraison_productpurshasepayementlivraison'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Commande avec payement à la carte bancaire', 'verbose_name_plural': 'Commandes avec payements à la carte bancaire'},
        ),
        migrations.AlterModelOptions(
            name='orderpayementlivraison',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Commande avec payement à la livraison', 'verbose_name_plural': 'Commandes avec payements à la livraison'},
        ),
        migrations.AlterModelOptions(
            name='productpurshase',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Produit payé avec payement à la livraison', 'verbose_name_plural': 'Produits payés avec payements à la livraison'},
        ),
        migrations.AlterModelOptions(
            name='productpurshasepayementlivraison',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Produit payé avec payement à la livraison', 'verbose_name_plural': 'Produits payés avec payements à la livraison'},
        ),
    ]
