# Generated by Django 2.0.7 on 2019-01-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180920_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpurshase',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Produit payé avec payement par carte bancaire', 'verbose_name_plural': 'Produits payés avec payements par carte bancaire'},
        ),
    ]
