# Generated by Django 2.0.7 on 2019-03-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoirecomputer',
            name='caracteristque',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
