# Generated by Django 2.0.7 on 2019-12-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoireclothng',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='accessoirecomputer',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='accessoirephone',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='culotte',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='jupe',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='menclothing',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='pantalon',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='tablette',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='womenclothing',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
    ]
