# Generated by Django 2.0.7 on 2019-03-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_accessoirecomputer_caracteristque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantalon',
            name='pantalon_type',
            field=models.CharField(choices=[('jeans', 'Pantalon Jeans'), ('jggin', 'Pantalon Jogging'), ('chino', 'Pantalon Chino'), ('tissu', 'Pantalon Tissu '), ('nilon', 'Pantalon en nilon'), ('mini', 'Pantalon en mini')], max_length=250),
        ),
    ]
