# Generated by Django 2.0.7 on 2019-03-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190323_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoireclothng',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessoirecomputer',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessoirephone',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='computer',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='culotte',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jupe',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menclothing',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menshoes',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pantalon',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phone',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablette',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='womenclothing',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='womenshoes',
            name='seller_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
