# Generated by Django 2.0.7 on 2019-12-23 13:51

from django.db import migrations, models
import utils.files_utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191216_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electromenager',
            name='caracteristique',
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='image_derriere',
            field=models.FileField(blank=True, null=True, upload_to=utils.files_utils.upload_file_location),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='image_devant',
            field=models.FileField(blank=True, null=True, upload_to=utils.files_utils.upload_file_location),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='image_dos',
            field=models.FileField(blank=True, null=True, upload_to=utils.files_utils.upload_file_location),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='image_droite',
            field=models.FileField(blank=True, null=True, upload_to=utils.files_utils.upload_file_location),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='image_gauche',
            field=models.FileField(blank=True, null=True, upload_to=utils.files_utils.upload_file_location),
        ),
        migrations.AlterField(
            model_name='menshoes',
            name='image_haut',
            field=models.FileField(blank=True, null=True, upload_to=utils.files_utils.upload_file_location),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='image_derriere',
            field=models.FileField(blank=True, null=True, upload_to=utils.files_utils.upload_file_location),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='image_devant',
            field=models.FileField(blank=True, null=True, upload_to=utils.files_utils.upload_file_location),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='image_dos',
            field=models.FileField(blank=True, null=True, upload_to=utils.files_utils.upload_file_location),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='image_droite',
            field=models.FileField(blank=True, null=True, upload_to=utils.files_utils.upload_file_location),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='image_gauche',
            field=models.FileField(blank=True, null=True, upload_to=utils.files_utils.upload_file_location),
        ),
        migrations.AlterField(
            model_name='womenshoes',
            name='image_haut',
            field=models.FileField(blank=True, null=True, upload_to=utils.files_utils.upload_file_location),
        ),
    ]
