# Generated by Django 2.0.7 on 2019-03-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190328_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoireclothng',
            name='seller_count',
        ),
        migrations.RemoveField(
            model_name='accessoirecomputer',
            name='seller_count',
        ),
        migrations.RemoveField(
            model_name='accessoirephone',
            name='seller_count',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='seller_count',
        ),
        migrations.RemoveField(
            model_name='culotte',
            name='seller_count',
        ),
        migrations.RemoveField(
            model_name='jupe',
            name='seller_count',
        ),
        migrations.RemoveField(
            model_name='menclothing',
            name='seller_count',
        ),
        migrations.RemoveField(
            model_name='menshoes',
            name='seller_count',
        ),
        migrations.RemoveField(
            model_name='pantalon',
            name='seller_count',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='seller_count',
        ),
        migrations.RemoveField(
            model_name='tablette',
            name='seller_count',
        ),
        migrations.RemoveField(
            model_name='womenclothing',
            name='seller_count',
        ),
        migrations.RemoveField(
            model_name='womenshoes',
            name='seller_count',
        ),
    ]
