# Generated by Django 2.0.7 on 2018-08-07 18:18

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='types_product',
            field=models.CharField(choices=[('phone', 'Phone'), ('tablette', 'Tablette'), ('computer', 'Computer'), ('cloths', 'Cloths'), ('shoe', 'Shoe'), ('food', 'Food'), ('fourniture', 'Fourniture'), ('food', 'Food'), ('materiel', 'Materiel'), ('pants', 'Pants')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/michel/galilee/static_cdn/protected_root'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
