# Generated by Django 2.0.7 on 2018-08-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180807_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='types_product',
            field=models.CharField(choices=[('phone', 'Phone'), ('tablette', 'Tablette'), ('computer', 'Computer'), ('cloths', 'Cloths'), ('shoe', 'Shoe'), ('food', 'Food'), ('fourniture', 'Fourniture'), ('materiel', 'Materiel'), ('pants', 'Pants'), ('electromenager', 'Electroménager')], default='', max_length=250),
        ),
    ]
