# Generated by Django 2.0.7 on 2018-08-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180812_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pseudo_name',
            field=models.CharField(default='phone', max_length=250),
        ),
    ]
