# Generated by Django 2.0.7 on 2018-08-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_pseudo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_marque',
            field=models.CharField(default='samsung', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.CharField(default='X', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='pseudo_name',
            field=models.CharField(max_length=250),
        ),
    ]
