# Generated by Django 2.0.7 on 2018-08-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180828_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_marque',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='types_product',
            field=models.CharField(choices=[('phone', 'Phone'), ('tablette', 'Tablette'), ('computer', 'Computer'), ('cloths', 'Cloths'), ('shoe', 'Shoe'), ('food', 'Food'), ('fourniture', 'Fourniture'), ('materiel', 'Materiel'), ('pants', 'Pants'), ('electromenager', 'Electroménager')], max_length=250),
        ),
    ]
