# Generated by Django 2.0.7 on 2018-08-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180828_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
