# Generated by Django 2.0.7 on 2018-08-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180828_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfile',
            old_name='file',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='types_product',
            field=models.CharField(choices=[('phone', 'Phone'), ('electronique', 'Electronique'), ('luxe', 'Luxe'), ('tablette', 'Tablette'), ('computer', 'Computer'), ('cloths', 'Cloths'), ('shoe', 'Shoe'), ('food', 'Food'), ('fourniture', 'Fourniture'), ('materiel', 'Materiel'), ('pants', 'Pants'), ('electromenager', 'Electroménager')], max_length=250),
        ),
    ]
