# Generated by Django 2.0.7 on 2018-08-29 01:37

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180829_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/michel/galilee/static_cdn/protected_root'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
