# Generated by Django 2.0.7 on 2018-08-29 02:52

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20180829_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='image',
            field=models.ImageField(upload_to=products.models.upload_product_file_loc),
        ),
    ]
