# Generated by Django 2.0.7 on 2018-09-20 17:06

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20180901_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=250, null=True, upload_to=products.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='image',
            field=models.ImageField(max_length=250, upload_to=products.models.upload_product_file_loc),
        ),
    ]
